[package]
name = "vecadd"
version = "0.1.0"
edition = "2024"

[dependencies]
nanorand = "0.8.0"
cust = { git = "https://github.com/Rust-GPU/Rust-CUDA.git", branch = "main", package = "cust" }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git", branch = "main", package = "cuda_builder" }

